---
title: "Untitled"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(dplyr,ggplot2,janitor,tidyr,stringr,stringi,hrbrthemes)
```

## Import data

This is an R Markdown format used for publishing markdown documents to GitHub. When you click the **Knit** button all R code chunks are run and a markdown file (.md) suitable for publishing to GitHub is generated.

## Including Code

You can include R code in the document as follows:

```{r participant data}
df <- readxl::read_excel(path = "participant_meta_data/participant_meta_data_FULL.xlsx",sheet = "Sheet1") %>% janitor::clean_names()
df <- readxl::read_excel(path = "participant_meta_data/New_participant_meta_data analysis.xlsx",sheet="clean_data") %>% janitor::clean_names()  
df
df <- df  %>% 
  mutate(experimentID=row_number()) %>% 
  mutate(id=paste(experimentID,participant_id)) %>% 
  group_by(id) %>% 
  mutate(experimentID = paste0(stri_rand_strings(1, 5, "[A-Z]"), stri_rand_strings(1, 4, "[0-9]"), stri_rand_strings(1, 1, "[A-Z]")))
  
 head(df) 
```
# 1.1 Summary table
```{r summary data}
df %>% 
  group_by(gender,toilet_type,activity) %>% 
  summarise(Mean=mean(total_duration),
            SD=sd(total_duration,na.rm = TRUE))
```

# 1.3 Plot summary data by gender and toilet type
```{r}

df %>% 
  ggplot() +
  geom_violin(aes(x=activity,y=total_duration,fill=gender),draw_quantiles = c(0.25,0.5,0.75))+
  # geom_jitter(aes(x=toilet_type,y=total_duration,fill=gender),width = 0.2)+
  facet_grid(~toilet_type,scales="free_x")+
  hrbrthemes::theme_ipsum()

```
# Hypothesis testing
```{r}
hist(log10(df$total_duration))

fit_aov <- aov(data=df,log10(total_duration)~gender+toilet_type) 

plot(fit_aov)

fit_aov %>% broom::tidy()
```


